# /metlife-TEN-Hackathon/Dockerfile.backend
FROM node:18-alpine
WORKDIR /app
COPY backend/package.json ./
COPY backend/package*.json ./
RUN npm ci --only=production
COPY backend/src ./src
EXPOSE 3001
RUN echo '#!/bin/sh' > /app/start.sh && \
    echo 'node src/config/runMigrations.js' >> /app/start.sh && \
    echo 'node src/index.js' >> /app/start.sh && \
    chmod +x /app/start.sh
CMD ["/app/start.sh"]
